// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adult': string;
  'child': string;
  'description': string;
  'info': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
