// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'block': string;
  'important': string;
  'primary': string;
  'secondary': string;
  'selected': string;
  'text': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
