// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'control': string;
  'disabled': string;
  'invalid': string;
  'plaintext': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
